clang mi2km.cpp -o mi2km.exe
clang enter2int.cpp -o enter2int.exe
clang enter2double.cpp -o enter2double.exe
clang 3int_sort.cpp -o 3int_sort.exe
clang 3str_sort.cpp -o 3str_sort.exe
clang odd_or_even.cpp -o odd_or_even.exe
clang spell_num.cpp -o spell_num.exe
clang cal2op.cpp -o cal2op.exe
clang money.cpp -o money.exe