# -*- MakeFile -*-

#target: prerequisites
#	recipe

all: 2 3 5 6 7 9 10 11

2: 2_name_pair.exe
3: 3_name_pair.exe
5: 5_library_main.exe
6: 6_library_main.exe
7: 7_library_main.exe
9: 9_library_main.exe
10: 10_leapyear.exe
11: 11_helper_funcs.exe

2_name_pair.exe: 2_name_pair.cpp
	clang 2_name_pair.cpp -o 2_name_pair.exe
	
3_name_pair.exe: 3_name_pair.cpp
	clang 3_name_pair.cpp -o 3_name_pair.exe
	
5_library_main.exe: 5_library_main.cpp
	clang 5_library_main.cpp -o 5_library_main.exe
	
6_library_main.exe: 6_library_main.cpp
	clang 6_library_main.cpp -o 6_library_main.exe
	
7_library_main.exe: 7_library_main.cpp
	clang 7_library_main.cpp -o 7_library_main.exe
	
9_library_main.exe: 9_library_main.cpp
	clang 9_library_main.cpp -o 9_library_main.exe
	
10_leapyear.exe: 10_leapyear.cpp
	clang 10_leapyear.cpp -o 10_leapyear.exe
	
11_helper_funcs.exe: 11_helper_funcs.cpp
	clang 11_helper_funcs.cpp -o 11_helper_funcs.exe
	